In [2]:
import numpy as np
distance_travelled = [110, 220, 510, 180, 210]
print(type(distance_travelled))
my_array = np.array(distance_travelled)
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
import numpy as np
new_array = np.array([[10, 9, 6],
       [1,2,5],
       [30,60,90],
       [3,4,5]])
print(new_array)
new_array[2,2]

[[10  9  6]
 [ 1  2  5]
 [30 60 90]
 [ 3  4  5]]


np.int64(90)